apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  namespace: lab01
  labels:
    app: init-demo
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  initContainers:
    - name: setup
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "<h1>Initialized!</h1>" > /workdir/index.html
          echo "Init container done."
      volumeMounts:
        - name: workdir
          mountPath: /workdir
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
  restartPolicy: Always
